inherit_from:
  - .rubocop_todo.yml

AllCops:
  # Exclude anything that isn't really part of our code.
  # rails_helper is excluded because it's full of solecisms, but it's mostly
  # generated code and copy-and-pasted snipets from READMEs.
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - '**/*.gemspec'
    - '**/Rakefile'
    - '**/Vagrantfile'
    - 'config/initializers/simple_form.rb'
    - 'config/unicorn.rb'
    - 'spec/rails_helper.rb'
    - 'spec/lib/**/*'
    - 'lib/tasks/**/*'
    - 'spec/dummy/db/**/*'
    - 'smoke_test'
    - 'spec/mailers/previews/*'
    - 'lib/generators/**/*'
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.0

Rails:
  Enabled: true

# Just indent parameters by two spaces. It's less volatile if methods change,
# and there's less busy work lining things up.
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Style/CollectionMethods:
  PreferredMethods:
    inject: 'inject'
    reduce: 'inject'

# Chain methods with trailing dots.
Layout/DotPosition:
  EnforcedStyle: trailing

# Percent-formatting and hash interpolation both have their place. Don't
# enforce any particular one.
Style/FormatString:
  Enabled: false

# It's not really clearer to replace every if with a return if.
Style/GuardClause:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# Don't worry about long methods in specs.
Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/**/*'

# Enforce single quotes everywhere except in specs (because there's a lot of
# human text with apostrophes in spec names, and using double quotes for all
# of those is more consistent. There shouldn't be much human-readable text in
# the application code: that is better moved to the locale files.
Style/StringLiterals:
  EnforcedStyle: single_quotes
  Exclude:
    - 'spec/**/*'

# Prefer sensible naming to comments everywhere.
Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false

# Would enforce do_y if x over if x / do y / end. As with GuardClause above,
# this enforces code organisation that doesn't necesarily make things clearer.
Style/IfUnlessModifier:
  Enabled: false

Style/CaseEquality:
  Enabled: false

# Allow safe assignment in conditions.
Lint/AssignmentInCondition:
  AllowSafeAssignment: false

Style/ClassAndModuleChildren:
  Enabled: false

require: rubocop-rspec

Style/RegexpLiteral:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/WordArray:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Metrics/ClassLength:
  CountComments: false
  Max: 120

Metrics/ModuleLength:
  Max: 115

RSpec/DescribeClass:
  Exclude:
    - 'spec/views/**/*'
    - 'spec/config/schedule_spec.rb'

Metrics/AbcSize:
  Exclude:
    - 'spec/support/profile.rb'

Rails/TimeZone:
  Exclude:
    - 'spec/**/*'

Rails/Date:
  Exclude:
    - 'spec/**/*'

Lint/Debugger:
  Exclude:
    - 'spec/**/*'

Style/SingleLineBlockParams:
  Enabled: false

Style/ClassVars:
  Exclude:
    - 'spec/**/*'

Layout/FirstArrayElementIndentation:
  Exclude:
    - 'spec/**/*'

Layout/SpaceAroundOperators:
  Enabled: false

Performance/TimesMap:
  Exclude:
    - 'spec/**/*'

Style/ZeroLengthPredicate:
  Exclude:
    - 'Gemfile'

RSpec/NotToNot:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

Rails/ScopeArgs:
  Enabled: false

# Switch off due to upgrade
Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/EmptyLineAfterExample:
  Enabled: false

Capybara/FeatureMethods:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/ContextMethod:
  Enabled: false

Capybara/CurrentPathExpectation:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/RepeatedExampleGroupBody:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Capybara/VisibilityMatcher:
  Enabled: false

RSpec/EmptyLineAfterHook:
  Enabled: false

Layout/MultilineBlockLayout:
  Enabled: false

Style/RedundantSort:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

FactoryBot/CreateList:
  Enabled: false

RSpec/LetBeforeExamples:
  Enabled: false

FactoryBot/AttributeDefinedStatically:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

RSpec/ReceiveNever:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/HooksBeforeExamples:
  Enabled: false

Layout/BlockEndNewline:
  Enabled: false

Layout/LeadingEmptyLines:
  Enabled: false

Style/RandomWithOffset:
  Enabled: false

RSpec/EmptyLineAfterExampleGroup:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

RSpec/ExpectChange:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Enabled: false

RSpec/ImplicitBlockExpectation:
  Enabled: false

RSpec/MultipleSubjects:
  Enabled: false

Rails/FilePath:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Rails/Presence:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false

Performance/EndWith:
  Enabled: false

Rails/LinkToBlank:
  Enabled: false

Rails/ApplicationController:
  Enabled: false

Performance/StringReplacement:
  Enabled: false

Lint/NonDeterministicRequireOrder:
  Enabled: false

Performance/InefficientHashSearch:
  Enabled: false

# New settings due to upgrade and switch it off for now
Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Lint/DeprecatedOpenSSLConstant:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: false

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/RedundantRegexpCharacterClass:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

